### ISSUE TITLE
ValueError: Unrecognised argument(s): encoding

### ISSUE THREAD

**Issue by oonisim** [areed1192/python-sec#5]
```
import sys
sys.path

sys.path.append('/home/oonisim/home/repository/git/oonisim/finance/alexreed/python-sec/')

from pprint import pprint
from edgar.client import EdgarClient
from edgar.enums import StateCodes
from edgar.enums import CountryCodes
from edgar.enums import StandardIndustrialClassificationCodes

# Initialize the Edgar Client
edgar_client = EdgarClient()

# Initialize the Company Services.
company_services = edgar_client.companies()

# Grab all the companies that are based in Texas.
pprint(company_services.get_companies_by_state(state_code='TX'))

# Grab all the companies that are based in Australia, same logic here with the Enums.
pprint(
    company_services.get_companies_by_country(
        country_code=CountryCodes.AUSTRALIA
    )
)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_7643/255480336.py in <module>
      6 
      7 # Initialize the Edgar Client
----> 8 edgar_client = EdgarClient()
      9 
     10 # Initialize the Company Services.

~/home/repository/git/oonisim/finance/alexreed/python-sec/edgar/client.py in __init__(self)
     24         """
     25 
---> 26         self.edgar_session = EdgarSession(client=self)
     27 
     28     def __repr__(self) -> str:

~/home/repository/git/oonisim/finance/alexreed/python-sec/edgar/session.py in __init__(self, client)
     45             pathlib.Path('logs/sec_api_log.log').touch()
     46 
---> 47         logging.basicConfig(
     48             filename="logs/sec_api_log.log",
     49             level=logging.INFO,

/usr/lib/python3.8/logging/__init__.py in basicConfig(**kwargs)
   2007             if kwargs:
   2008                 keys = ', '.join(kwargs.keys())
-> 2009                 raise ValueError('Unrecognised argument(s): %s' % keys)
   2010     finally:
   2011         _releaseLock()

ValueError: Unrecognised argument(s): encoding

```

**Comment by areed1192** [comment]
Found the issue, in python 3.8 the `logging.basicConfig()` function doesn't allow for the `encoding` argument. Hence why you were getting the error. It looks like they added it in python 3.9, so what I did is added a check for the user's python version. If it's below 3.9 it won't add the encoding argument.

**Comment by aaronclong** [comment]
I am having this issue as well. The library's *setup.py* says it supports *python 3.7* and up.

I wonder if you would reconsider how you do logging in the library? The library makes assumptions about how the user wants to log, and [it goes against best practices recommended by the Python core team](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library). In general, library loggers should only use the [NullHandler](https://docs.python.org/3/library/logging.handlers.html#nullhandler) to let the user decide on the format and location to log.  Let me know if you have any questions regarding this, more than willing to clarify further.

![Screenshot from 2022-02-21 00-24-47](https://user-images.githubusercontent.com/7354981/154894698-b23bc76c-e99b-4a02-be33-cfbccff3ab49.png).

**Comment by aaronclong** [comment]
I have a WIP of this idea here: https://github.com/areed1192/python-sec/pull/9

It isn't ready yet, but it demonstrates the idea.
